export const projectsData = [
    {
        id: 1,
        image: '/project.png',
        title: 'FoodSure Website UI',
        description: 'A clean and intuitive UI design for a fast food delivery platform. Focused on enhancing user experience through simple navigation, quick checkout, and mobile responsiveness. Designed to make ordering food fast, fun, and frustration-free.',
        URL: 'https://mohamadelhadidy.com/',
        GitHub: 'https://github.com/MohamadElhadidy',
        Behance: 'https://www.behance.net/mohamadelhadidy98',
        Dribble: 'https://dribbble.com/MohamadElhadidy',
    },
    {
        id: 2,
        image: '/project2.png',
        title: 'Foodle – Fast Food Website UI',
        description: 'A clean and intuitive UI design for a fast food delivery platform. Focused on enhancing user experience through simple navigation, quick checkout, and mobile responsiveness. Designed to make ordering food fast, fun, and frustration-free.',
        Behance: 'https://www.behance.net/mohamadelhadidy98',
        Dribble: 'https://dribbble.com/MohamadElhadidy',
    },
    {
        id: 3,
        image: '/project.png',
        title: 'Foodle – Fast Food Website UI',
        description: 'A clean and intuitive UI design for a fast food delivery platform. Focused on enhancing user experience through simple navigation, quick checkout, and mobile responsiveness. Designed to make ordering food fast, fun, and frustration-free.',
        URL: 'https://mohamadelhadidy.com/',
        GitHub: 'https://github.com/MohamadElhadidy',
    },
    {
        id: 4,
        image: '/project.png',
        title: 'Foodle – Fast Food Website UI',
        description: 'A clean and intuitive UI design for a fast food delivery platform. Focused on enhancing user experience through simple navigation, quick checkout, and mobile responsiveness. Designed to make ordering food fast, fun, and frustration-free.',
        URL: 'https://mohamadelhadidy.com/',
        GitHub: 'https://github.com/MohamadElhadidy',
    },
    {
        id: 5,
        image: '/project.png',
        title: 'Foodle – Fast Food Website UI',
        description: 'A clean and intuitive UI design for a fast food delivery platform. Focused on enhancing user experience through simple navigation, quick checkout, and mobile responsiveness. Designed to make ordering food fast, fun, and frustration-free.',
        URL: 'https://mohamadelhadidy.com/',
        GitHub: 'https://github.com/MohamadElhadidy',
    },
    {
        id: 6,
        image: '/project.png',
        title: 'Foodle – Fast Food Website UI',
        description: 'A clean and intuitive UI design for a fast food delivery platform. Focused on enhancing user experience through simple navigation, quick checkout, and mobile responsiveness. Designed to make ordering food fast, fun, and frustration-free.',
        URL: 'https://mohamadelhadidy.com/',
        GitHub: 'https://github.com/MohamadElhadidy',
    },
    {
        id: 7,
        image: '/project.png',
        title: 'Foodle – Fast Food Website UI',
        description: 'A clean and intuitive UI design for a fast food delivery platform. Focused on enhancing user experience through simple navigation, quick checkout, and mobile responsiveness. Designed to make ordering food fast, fun, and frustration-free.',
        URL: 'https://mohamadelhadidy.com/',
        GitHub: 'https://github.com/MohamadElhadidy',
    },
    {
        id: 8,
        image: '/project.png',
        title: 'Foodle – Fast Food Website UI',
        description: 'A clean and intuitive UI design for a fast food delivery platform. Focused on enhancing user experience through simple navigation, quick checkout, and mobile responsiveness. Designed to make ordering food fast, fun, and frustration-free.',
        URL: 'https://mohamadelhadidy.com/',
        GitHub: 'https://github.com/MohamadElhadidy',
    },
    {
        id: 9,
        image: '/project.png',
        title: 'Foodle – Fast Food Website UI',
        description: 'A clean and intuitive UI design for a fast food delivery platform. Focused on enhancing user experience through simple navigation, quick checkout, and mobile responsiveness. Designed to make ordering food fast, fun, and frustration-free.',
        URL: 'https://mohamadelhadidy.com/',
        GitHub: 'https://github.com/MohamadElhadidy',
    },

    

]